name: etp_data
description: Data Service
version: 1.0.0

environment:
  sdk: '>=2.18.6 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
dependencies:
  conduit: ^4.2.0
  conduit_core: ^4.2.0
  jaguar_jwt: ^3.0.0
dependency_overrides:
  file: ^6.1.4
